apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: env-test
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: probe
            envBlock: '[{"name": "DD_ARCANNA_ES_METRIC_COLLECTOR_PWD", "valueFrom": {"secretKeyRef": {"name": "datadog-arcanna-es-password-secret", "key": "password"}}}]'
  template:
    metadata:
      name: '{{name}}-env-test'
    spec:
      project: default
      source:
        repoURL: https://github.com/gn-cin-cout/arcanna-deploy.git
        targetRevision: main
        path: env-test/charts/probe
        helm:
          parameters:
            - name: envBlock
              value: '{{envBlock}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: env-test
      syncPolicy:
        automated: {selfHeal: true, prune: true}
        syncOptions: [CreateNamespace=true]
